q_01 = []

print(q_01)
q_01.append("A")
print(q_01)
q_01.append("B")
print(q_01)
removed = q_01.pop()
print(f"removed is {removed}")
print(q_01)
q_01.append("C")
print(q_01)
removed = q_01.pop()
print(f"removed is {removed}")
print(q_01)
q_01.append("D")
removed = q_01.pop()
print(f"removed is {removed}")
print(q_01)
removed = q_01.pop()
print(f"removed is {removed}")
print(q_01)